package com.vinni.dndcharacterlist.core.domain.model

data class CharacterUpsert(
    val id: Long? = null,
    val ruleset: String? = null,
    val name: String,
    val classId: String? = null,
    val characterClass: String,
    val subclassId: String? = null,
    val subclass: String,
    val raceId: String? = null,
    val race: String,
    val subraceId: String? = null,
    val alignment: String,
    val backgroundId: String? = null,
    val background: String,
    val level: Int,
    val abilityMethod: String? = null,
    val armorClass: Int,
    val hitPoints: Int,
    val hitPointsMax: Int? = null,
    val strength: Int,
    val dexterity: Int,
    val constitution: Int,
    val intelligence: Int,
    val wisdom: Int,
    val charisma: Int,
    val savingThrowProficiencies: List<String>? = null,
    val skillProficiencies: List<String>? = null,
    val notes: String
)
